@startuml

!define MANUFACTURER #CDE0FF
!define VIBW #7ED321
!define BFARM #F5A623

title HDDT FHIR Data Model (complete)
skinparam packageStyle rectangle

package HDDT_Measurements_and_Devices as "Device Data Recorde Manufacturer" MANUFACTURER {
    
    class IV as "Interoperable Value" <<FHIR Observation>> {
        status : status of the measured value [1..1]
        code : classification of the measured value [1..1]
        date : date or period of the measurement [1..1]
        value : outcome of the measurement [1..1]
    }

    class Metric as "Sensor Type and Calibration Status" <<FHIR DeviceMetric>> {
        type : kind of value measured by the sensor [1..1]
        calibration.state : quality indicator for measurements [1..1]
    }

    class PHD as "Personal Health Device" <<FHIR Device>> {
        type : machine-readable device type
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
        serialNumber : serial number [1..1]
        expirationDate : end of life date [0..1]
        property : additional properties [0..*]
    }

'    class DDR as "Device Data Recorder" <<FHIR Device>> {
'        type = 462240000|SCT [1..1]
'        status : operational status [1..1]
'        deviceName : product name [1..1]
'        manufacturer : name of the manufacturer [0..1]
'        property : additional properties [0..*]
'    }

    () "{xor}" as xor

    IV -> xor : "device [1..1] "
    xor -> Metric 
    xor --> PHD 
    Metric --> PHD : "source [1..1]"
'    PHD -> DDR : "parent [1..1]"
} 

package HDDT_Registries as "Device Definitions (HDDT Registries at BfARM)" BFARM {

    class PHD_Def as "Personal Health Device Definition" <<FHIR DeviceDefinition>> {
        type : kind of device <<SCT or ISO/IEEE 11073 code>> [1..1]
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
        property : additional properties [0..*]
    }

    class DM_Def as "Device Data Recorder Definition" <<FHIR DeviceDefinition>> {
        type = 462240000|SCT [1..1]
        status : status of the registration process [1..1]
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
        property : additional properties [0..*]
    }

    class DDR_Endpoint as "Device Data Recorder FHIR Endpoint" <<FHIR Endpoint>> {
        address : canonical URL for the endpoint [1..1]
        status : status of the endpoint [1..1]
    }

    DM_Def .left.> DDR_Endpoint : "getEndpoint()"
}

PHD --> PHD_Def : "definition [1..1]"
' DDR --> DM_Def : "definition [1..1]"
PHD_Def .. DM_Def : "getDevices()\ngetRecorders()"

@enduml