@startuml
!include fbeta-theme.puml
hide footbox
!pragma teoz true

!define MANUFACTURER #A0C5CF
!define VIBW #C9E6CA
!define BFARM #F6D7B6
!define SPEC #FAF3C0

title HDDT Object Model Example (Continuous Glucose Measurement)
skinparam packageStyle rectangle

package HDDT_Measurements_and_Devices as "FHIR SearchSet in Response to a DiGA's Request for Device Data" MANUFACTURER {

    object "CGM-1" as IV1 <<Observation Continuous Glucose Measurement>> {
        status = final
        code = 99504-3|LOINC "Glucose [Mass/volume] in Interstitial fluid"
        effectivePerid = 2025-09-26T16:00:00Z - 2025-09-26T16:59:59Z
        valueSampledData.origin.system = UCUM
        valueSampledData.origin.code = mg/dL|mmol/L
        valueSampledData.period : 300000 ms
        valueSampledData.dimensions = 1
        valueSampledData.data = 123 122 126 134 129 128 130 131 129 127 127 133
    }

    object "CGM-2" as IV2 <<Observation Continuous Glucose Measurement>> {
        status = preliminary
        code = 99504-3|LOINC "Glucose [Mass/volume] in Interstitial fluid"
        effectivePerid = 2025-09-26T17:00:00Z - 2025-09-26T17:59:59Z
        valueSampledData.origin.system = UCUM
        valueSampledData.origin.code = mg/dL|mmol/L
        valueSampledData.period : 300000 ms
        valueSampledData.dimensions = 1
        valueSampledData.data = 135 118 126 122 
    }

    class DR as "CGM Summary Report\n<<FHIR Bundle>>" {
        code = 107931-8|LOINC "Continuous glucose monitoring summary panel"
        date : period covered by the report
    }

    object "Glucose Sensor Type and Calibration Status" as Metric <<FHIR DeviceMetric>> {
        type = 29140|iso:11073:10101
        unit = mg/dL|UCUM
        calibration.state = calibrated
    }

    object "rtCGM" as PHD <<FHIR Device>> {
        status = active
        type = 528409|iso:11073:10101
        deviceName = "GlukkoCGM 18"
        manufacturer = "Glukko Inc."
        serialNumber = "CGM1234567890
    }

    IV2 --> Metric : "device"
    IV1 --> Metric : "device"
    DR --> PHD : "entry:Observation.device"
    Metric -> PHD : "source"
}


@enduml