@startuml
!include fbeta-theme.puml
hide footbox
!pragma teoz true

!define MANUFACTURER #A0C5CF
!define VIBW #C9E6CA
!define BFARM #F6D7B6
!define SPEC #FAF3C0

title Profiling of the HDDT Information Model for the MIV Continuous Glucose Measurement 
skinparam packageStyle rectangle

package HDDT_Measurements_and_Devices as "Device Data Recorder Manufacturer" MANUFACTURER {
    
    class IV as "Interoperable Value" <<FHIR Observation>> {
        status = final | preliminary
        code : classification of the measured value [1..1]
        effectivePeriod : period of the measurement [1..1]
        valueSampledData.origin.system = UCUM
        valueSampledData.origin.code = mg/dL|mmol/L
        valueSampledData.period : time between samples in ms [1..1]
        valueSampledData.dimensions = 1
        valueSampledData.data : series of measurements [1..1]
    }

    class DR as "CGM Summary Report\n<<FHIR Bundle>>" {
        code = 107931-8|LOINC "Continuous glucose monitoring summary panel"
        date : period covered by the report
    }
    IV <.. DR : "based on"

    class Metric as "Sensor Type and Calibration Status" <<FHIR DeviceMetric>> {
        type : kind of value measured by the sensor [0..1]
        calibration.state : quality indicator for measurements [1..1]
        calibration.time : last calibration date [1..1]
    }

    class PHD as "Personal Health Device" <<FHIR Device>> {
        type : machine-readable device type [0..1]
        deviceName : product name [0..1]
        manufacturer : name of the manufacturer [0..1]
        serialNumber : serial number [0..1]
        expirationDate : end of communication date [0..1]
        property : additional properties [0..*]
    }

    () "{xor}" as xor

    IV -left-> xor : "device [1..1] "
    xor -left-> Metric 
    xor --> PHD 
    Metric --> PHD : "source [1..1]"
} 

package gematik as "Repository for gematik FHIR IGs" SPEC {
    object "Bundle - Summary Data Measurements" as RP <<FHIR StructureDefinition>> {
        name = "HddtCgmSummary"
        type = Bundle
        baseDefinition = <<FHIR Bundle>>
        derivation = constraint
   }

    object "Observation - Continuous Glucose Measurement" as OP <<FHIR StructureDefinition>> {
        name = "HddtContinuousGlucoseMeasurement"
        type = Observation
        baseDefinition = <<FHIR Observation>>
        derivation = constraint
    }
}

package "HIIS-VZ (Device Registry at BfARM)" as HDDT_Registries BFARM {

    object "Personal Health Device Definition" as PHD_Def <<FHIR DeviceDefinition>> {
        type : kind of device <<SCT or ISO/IEEE 11073 code>> [1..1]
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
        property[0] = (Real-Time-Delay, ...)
        property[1] = (Grace-Period, ...)
        property[2] = (Historic-Data-Period, ...)
        property[3] = (Chunk-Time-Span, ..., ...)
    }
}

package ZTS as "MIV Definitions (ZTS)" VIBW {
    enum "VS MIV Continuous Glucose Measurement" as MIV  <<FHIR ValueSet>> {
        url = " https://gematik.de/fhir/hddt/\n           ValueSet/hddt-miv-blood-glucose-measurement"
        version = "1.0.0"
        title = "ValueSet - Continuous Glucose Measurement from LOINC"
        name = "HddtMivContinuousGlucoseMeasurement"
        description = "key metrics and continuous monitoring"
        compose.include = 99504-3|LOINC, 105272-9|LOINC
    }
}

'IV::code --> MIV : "included with"
'Metric::type --> MIV : "included with"

PHD --> PHD_Def : "definition"
MIV <.down. OP : "implements"
IV <. OP : "defines"
IV::code .> MIV : "included with"
DR <. RP : "defines"


@enduml