@startuml

!define MANUFACTURER #A0C5CF
!define VIBW #C9E6CA
!define BFARM #F6D7B6
!define SPEC #FAF3C0

title HDDT Object Model Example (Blood Glucose Measurement)
skinparam packageStyle rectangle

package HDDT_Measurements_and_Devices as "FHIR SearchSet in Response to a DiGA's Request for Device Data" MANUFACTURER {

    object "Blood Glucose Measurement 2" as IV2 <<Observation Blood Glucose>> {
        status = final
        code = 2339-0|LOINC "Blood Glucose"
        date = 20250926:1630+0200
        value = 129 mg/dL
    }

    object "Blood Glucose Measurement 1" as IV1 <<Observation Blood Glucose>> {
        status = final
        code = 2339-0|LOINC "Blood Glucose"
        date = 20250926:1200+0200
        value = 120 mg/dL
    }

    object "Glucose Sensor Type and Calibration Status" as Metric <<FHIR DeviceMetric>> {
        type = 29112|iso:11073:10101
        calibration.state = calibrated
    }

    object "Glucose Meter" as PHD <<FHIR Device>> {
        type = 528401|iso:11073:10101
        deviceName = "glucocheck plus"
        manufacturer = "gluko inc."
        serialNumber = "123456789"
    }

    IV2 --> Metric : "device"
    IV1 --> Metric : "device"
    Metric -> PHD : "source"
}

package "Repository for gematik FHIR IGs" as gematik SPEC {
    object "Observation Blood Glucose Profile" as OP <<FHIR StructureDefinition>> {
        name = "Observation_Blood_Glucose"
        type = Observation
        baseDefinition = <<FHIR Observation>>
        derivation = constraint
    }
}

package "ZTS (German Central Terminology Server)" as ZTS VIBW {
    enum "Blood_Glucose_Value" as MIV  <<FHIR ValueSet>> {
        url = " https://terminologien.bfarm.de/fhir/ValueSet/VS-Blood-Glucose-Value"
        version = "1.0.0"
        title = "Blood Glucose Value"
        name = "VS_Blood_Glucose_Value"
        description = "LOINC codes for blood glucose measurements"
        compose.include = 2339-0|LOINC, 15074-8|LOINC, ...
    }
}

package "HiMi-SST-VZ (Device Registry at BfARM)" as HDDT_Registries BFARM {

    object "Personal Health Device Definition" as PHD_Def <<FHIR DeviceDefinition>> {
        type = 528401|iso:11073:10101
        deviceName = "glucocheck plus"
        manufacturer = "gluko inc."
        property[0] = (Store-Capacity-Count, 200)
        property[1] = (Real-Time-Delay, 15 minutes)
        property[2] = (Grace-Period, 15 minutes)
        property[3] = (Historic-Data-Period, 90 days)
    }
}

PHD --> PHD_Def : "definition"
MIV <.up. OP : "implements"
IV1 <. OP : "defines"
IV1::code ..> MIV : "included with"


@enduml