@startuml
!include fbeta-theme.puml
hide footbox
!pragma teoz true

!define MANUFACTURER #A0C5CF
!define VIBW #C9E6CA
!define BFARM #F6D7B6
!define SPEC #FAF3C0

title Profiling of the HDDT Information Model for the MIV Blood Glucose Measurement 
skinparam packageStyle rectangle

package HDDT_Measurements_and_Devices as "Device Data Recorder Manufacturer" MANUFACTURER {
    
    class IV as "Interoperable Value" <<FHIR Observation>> {
        status = final
        code : classification of the measured value [1..1]
        effectiveDateTime : date and time of the measurement [1..1]
        valueQuantity.value : quantity value of the measurement [1..1]
        valueQuantity.system = UCUM
        valueQuantity.code = mg/dL|mmol/L
    }

    class Metric as "Sensor Type and Calibration Status" <<FHIR DeviceMetric>> {
        type : kind of value measured by the sensor [0..1]
        calibration.state : quality indicator for measurements [1..1]
        calibration.time : last calibration date [1..1]
    }

    class PHD as "Personal Health Device" <<FHIR Device>> {
        type : machine-readable device type [0..1]
        deviceName : product name [0..1]
        manufacturer : name of the manufacturer [0..1]
        serialNumber : serial number [0..1]
        expirationDate : end of life date [0..1]
    }

    () "{xor}" as xor

    IV -left-> xor : "device [1..1] "
    xor -left-> Metric 
    xor --> PHD 
    Metric --> PHD : "source [1..1]"
} 

package gematik as "Repository for gematik FHIR IGs" SPEC {
    object "Observation - Blood Glucose Measurement" as OP <<FHIR StructureDefinition>> {
        name = "HddtBloodGlucoseMeasurement"
        type = Observation
        baseDefinition = <<FHIR Observation>>
        derivation = constraint
    }
}

package "HIIS-VZ (Device Registry at BfArM)" as HDDT_Registries BFARM {

    object "Personal Health Device Definition" as PHD_Def <<FHIR DeviceDefinition>> {
        type : kind of device <<SCT or ISO/IEEE 11073 code>> [1..1]
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
    }
}

package ZTS as "MIV Definitions (ZTS)" VIBW {
    enum "VS MIV Blood Glucose Measurement" as MIV  <<FHIR ValueSet>> {
        url = " https://gematik.de/fhir/hddt/\n           ValueSet/hddt-miv-blood-glucose-measurement"
        version = "1.0.0"
        title = "ValueSet - Blood Glucose Measurement from LOINC"
        name = "HddtMivBloodGlucoseMeasurement"
        description = "therapy mgmt and clinical decisions"
        compose.include = 2339-0|LOINC, 15074-8|LOINC, ...
    }
}

'IV::code --> MIV : "included with"
'Metric::type --> MIV : "included with"

PHD --> PHD_Def : "definition"
MIV <.up. OP : "implements"
IV <. OP : "defines"
IV::code .> MIV : "included with"

@enduml