@startuml

!define MANUFACTURER #CDE0FF
!define VIBW #7ED321
!define BFARM #F5A623

title HDDT FHIR Data Model (Medical Aids and Implants)
skinparam packageStyle rectangle

package HDDT_Measurements_and_Devices as "Measurements and Devices \n(implemented by the manufacturer; accessible via the HDDT API)"MANUFACTURER {
    
    class IV as "Interoperable Value" <<FHIR Observation>> {
        status : status of the measured value [1..1]
        code : classification of the measured value [1..1]
        date : date or period of the measurement [1..1]
        value : outcome of the measurement [1..1]
    }

    class Metric as "Sensor Type and Calibration Status" <<FHIR DeviceMetric>> {
        type : kind of value measured by the sensor [1..1]
        unit : unit of measurement [0..1]
        calibration.state : quality indicator for measurements [0..1]
    }

    IV::code --> Metric::type : "corresponds to"

    class PHD as "Personal Health Device" <<FHIR Device>> {
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
        serialNumber : serial number [1..1]
        expirationDate : end of life date [0..1]
        property : additional properties [0..*]
    }

    class DM as "Device Data Recorder" <<FHIR Device>> {
        status : operational status [1..1]
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
        property : additional properties [0..*]
    }

    IV --> Metric : "device [1..1] "
    Metric --> PHD : "source [1..1]"
    PHD --> DM : "parent [1..1]"
}

package HDDT_Registries as "Device Definitions (HDDT Registries at BfARM)" BFARM {

    class PHD_Def as "Personal Health Device Registry Entry" <<FHIR DeviceDefinition>> {
        type : kind of device <<SCT or ISO/IEEE 11073 code>> [1..1]
        deviceName : product name [1..1]
        manufacturer : name of the manufacturer [0..1]
        property : additional properties [0..*]
    }

    class DM_Def as "Device Data Recorder Registry Entry" <<FHIR DeviceDefinition>> {
        type = 462240000|SCT [1..1]
        deviceName : name of the aggregator [1..1]
        manufacturer : name of the manufacturer [0..1]
        property : additional properties [0..*]
    }

    class DM_Org as "Device Data Recorder Organization" <<FHIR Organization>> {
    }
    class EP as "HDDT Endpoints" <<FHIR Endpoint>> {
        status : operational status [1..1]
        connectionType: Coding <<hl7-fhir-rest | oauth2-authz>>
        address: URL of the endpoint [1..1]
    }

    DM_Def *-- DM_Org : "organization [1..1]"
    DM_Org *- EP : "endpoint [2..2]"
}

DM -left-> DM_Def : "definition [1..1]"
PHD -left-> PHD_Def : "definition [1..1]"

package ZTS as "MIV Definitions (German Central Terminology Server)" VIBW {
    enum MIV {
        url : canonical URL for the MIV [1..1]
        version : version of the MIV [1..1]
        title : human-friendly name of the MIV [1..1]
        name : machine-friendly name of the MIV [0..1]
        description : human-readable description of the MIV [1..1]
        compose.include : MIV defining concepts [1..*]
    }
}

'IV::code --> MIV : "included with"
'Metric::type --> MIV : "included with"

PHD_Def -up-> MIV : "capability [1..*]"
DM_Def -up-> MIV : "capability [1..*]"

@enduml