@startuml

!define HERSTELLER #CDE0FF
!define VIBW #7ED321
!define BFARM #F5A623

title FHIR Datenmodell für HiMi-DiGA Schnittstelle\\n(Blutzucker-Beispiel)
skinparam packageStyle rectangle

	package Versicherten_spezifische_FHIR_Ressourcen HERSTELLER {
        class vibW_Blutzucker <<FHIR Observation>> {
			code: "LOINC:2339-0"
			valueQuantity.value: "90"
			valueQuantity.unit: "mg/dl"
			valueQuantity.system: "UCUM"
            device: Reference(DeviceMetric)
            
        }
        class Gerätekonfiguration_glukometer <<FHIR DeviceMetric>> {
			unit: "UCUM:mg/dL"
			calibrationStatus: "calibrated"
            source: Reference(Device)
		}
        class Geräteinstanz_glukometer <<FHIR Device>> {
            deviceName: "Accu Chek mobile"
			manufacturer: "<hersteller_name>"
 			serialNumber: "2937459287531567"
            definition: Reference(DeviceDefinition)
        }

        vibW_Blutzucker --> Gerätekonfiguration_glukometer : "[1..1] device"
        Gerätekonfiguration_glukometer --> Geräteinstanz_glukometer : "[1..1] source"
    }

    package 374a_Enablement HERSTELLER {
        class DatenSchnittstelle <<FHIR CapabilityStatement>> {
			title: "374-API <himi_hersteller_name>"    
			format: "json"
            rest.resource.type: "Observation"
			rest.resource.searchParam: "patient, date"
            +rest.resource.interaction: "read", "search-type"
			rest.resource.profile: "SD_vibW_Blutzucker"
            rest.security.service.coding.code: "SMART-on-FHIR"
        }

    }

    package vibW_Wertelisten VIBW {

        class "VS_Blutzucker" as VS_BZ <<FHIR ValueSet>> {
			LOINC:2339-0
			LOINC:15074-8
        }
        class VS_HiMi_DeviceType <<FHIR ValueSet>> {
            compose.include[0].system: CS_HiMi_DeviceType
        }

		class VS_Blutzucker_Einheiten <<FHIR ValueSet>> {
			UCUM: mg/dL
			UCUM: mmol/l
		}
    }

    package vibW_Kodiersysteme VIBW {
        class CS_HiMi_DeviceType <<FHIR CodeSystem>> {
            Glukometer
            Backendsystem des Glukometer-Herstellers
            ...
        }
    }

    VS_HiMi_DeviceType --> CS_HiMi_DeviceType : "[1..1] compose.include.system"
   


package "Hersteller_spezifische FHIR_Ressourcen" BFARM {
    class DD_Sensor_AccuChekMobile <<FHIR DeviceDefinition>> {
		identifier: "30.34.02.0033"
        deviceName: "Accu-Chek Mobile U1"
		manufacturer: "<sensor_hersteller_name>"
		type: "Glukometer"
        capability.type: "LOINC:2339-0"
        capability.description: "Blutzucker Messung"
		property.valueCode: "mg/dL"
		property.valueRange: "10 - 660"
        parentDevice: Reference(DeviceDefinition) 
    }
        DD_Sensor_AccuChekMobile::type --> VS_HiMi_DeviceType : "[1..*] type.binding.valueSet"
		DD_Sensor_AccuChekMobile::property.valueCode --> VS_Blutzucker_Einheiten : "[1..*] property.valueCode.binding.valueSet"
        DD_Sensor_AccuChekMobile::capability.type --> VS_HiMi_ACM_SupportedVibW : "[1..*] capability.type.binding.valueSet"
    class D_HiMi_374a_Backend <<FHIR DeviceDefinition>> {
        manufacturer: "<himi_hersteller_name>"		
		deviceName: "<himi_name> § 374a SGB V APIs"
		type: "des Glukometer-Herstellers"		
		url: "<backend_url/url_resourceserver>"

    }
    D_HiMi_374a_Backend::type --> VS_HiMi_DeviceType : "[1..*] type.binding.valueSet"
	class VS_HiMi_ACM_SupportedVibW <<FHIR ValueSet>> {
		LOINC:2339-0
	}

    D_HiMi_374a_Backend <-- DD_Sensor_AccuChekMobile : "[*..1] parentDevice"


}

'* Profile-Abhängigkeiten



'* Capability Statement Referenzen
DatenSchnittstelle --> vibW_Blutzucker : "[1..*] supported base profiles"

VS_HiMi_ACM_SupportedVibW --> VS_BZ : "[1..1] subset of"
vibW_Blutzucker::code --> VS_BZ : "[1..*] valueset binding for code"
Geräteinstanz_glukometer --> DD_Sensor_AccuChekMobile : "[1..1] definition"
vibW_Blutzucker::valueQuantity.unit --> VS_Blutzucker_Einheiten : "[1..*] valueQuantity.unit.binding.valueSet"



@enduml