@startuml
!include fbeta-theme.puml
hide footbox
!pragma teoz true

!define MANUFACTURER #A0C5CF
!define VIBW #C9E6CA
!define BFARM #F6D7B6
!define SPEC #FAF3C0

title FHIR Data Model for HiMi-DiGA Interface\n(Blood Glucose Example)
skinparam packageStyle rectangle

	package Insured_Specific_FHIR_Resources MANUFACTURER {
        class vibW_Blood_Glucose <<FHIR Observation>> {
			code: "LOINC:2339-0"
			valueQuantity.value: "90"
			valueQuantity.unit: "mg/dl"
			valueQuantity.system: "UCUM"
            device: Reference(DeviceMetric)
            
        }
        class Device_Configuration_Glucometer <<FHIR DeviceMetric>> {
			unit: "UCUM:mg/dL"
			calibrationStatus: "calibrated"
            source: Reference(Device)
		}
        class Device_Instance_Glucometer <<FHIR Device>> {
            deviceName: "Accu Chek mobile"
			manufacturer: "<manufacturer_name>"
 			serialNumber: "2937459287531567"
            definition: Reference(DeviceDefinition)
        }

        vibW_Blood_Glucose --> Device_Configuration_Glucometer : "[1..1] device"
        Device_Configuration_Glucometer --> Device_Instance_Glucometer : "[1..1] source"
    }

    package 374a_Enablement MANUFACTURER {
        class Data_Interface <<FHIR CapabilityStatement>> {
			title: "374-API <himi_manufacturer_name>"    
			format: "json"
            rest.resource.type: "Observation"
			rest.resource.searchParam: "patient, date"
            +rest.resource.interaction: "read", "search-type"
			rest.resource.profile: "SD_vibW_Blood_Glucose"
            rest.security.service.coding.code: "SMART-on-FHIR"
        }

    }

    package vibW_ValueSets VIBW {

        class "VS_Blood_Glucose" as VS_BZ <<FHIR ValueSet>> {
			LOINC:2339-0
			LOINC:15074-8
        }
        class VS_HiMi_DeviceType <<FHIR ValueSet>> {
            compose.include[0].system: CS_HiMi_DeviceType
        }

		class VS_Blood_Glucose_Units <<FHIR ValueSet>> {
			UCUM: mg/dL
			UCUM: mmol/l
		}
    }

    package vibW_CodeSystems VIBW {
        class CS_HiMi_DeviceType <<FHIR CodeSystem>> {
            Glucometer
            Backend system of the glucometer manufacturer
            ...
        }
    }

    VS_HiMi_DeviceType --> CS_HiMi_DeviceType : "[1..1] compose.include.system"
   


package "Manufacturer_Specific_FHIR_Resources" BFARM {
    class DD_Sensor_AccuChekMobile <<FHIR DeviceDefinition>> {
		identifier: "30.34.02.0033"
        deviceName: "Accu-Chek Mobile U1"
		manufacturer: "<sensor_manufacturer_name>"
		type: "Glucometer"
        capability.type: "LOINC:2339-0"
        capability.description: "Blood glucose measurement"
		property.valueCode: "mg/dL"
		property.valueRange: "10 - 660"
        parentDevice: Reference(DeviceDefinition) 
    }
        DD_Sensor_AccuChekMobile::type --> VS_HiMi_DeviceType : "[1..*] type.binding.valueSet"
		DD_Sensor_AccuChekMobile::property.valueCode --> VS_Blood_Glucose_Units : "[1..*] property.valueCode.binding.valueSet"
        DD_Sensor_AccuChekMobile::capability.type --> VS_HiMi_ACM_SupportedVibW : "[1..*] capability.type.binding.valueSet"
    class D_HiMi_374a_Backend <<FHIR DeviceDefinition>> {
        manufacturer: "<himi_manufacturer_name>"		
		deviceName: "<himi_name> § 374a SGB V APIs"
		type: "type of the glucometer manufacturer"		
		url: "<backend_url/url_resourceserver>"

    }
    D_HiMi_374a_Backend::type --> VS_HiMi_DeviceType : "[1..*] type.binding.valueSet"
	class VS_HiMi_ACM_SupportedVibW <<FHIR ValueSet>> {
		LOINC:2339-0
	}

    D_HiMi_374a_Backend <-- DD_Sensor_AccuChekMobile : "[*..1] parentDevice"


}


Data_Interface --> vibW_Blood_Glucose : "[1..*] supported base profiles"

VS_HiMi_ACM_SupportedVibW --> VS_BZ : "[1..1] subset of"
vibW_Blood_Glucose::code --> VS_BZ : "[1..*] valueset binding for code"
Device_Instance_Glucometer --> DD_Sensor_AccuChekMobile : "[0..1] definition"
vibW_Blood_Glucose::valueQuantity.unit --> VS_Blood_Glucose_Units : "[1..*] valueQuantity.unit.binding.valueSet"



@enduml