@startuml

!include fbeta-theme.puml
'!include gematik-theme.puml
hide footbox
!pragma teoz true

' ===== Aliases for participants =====
!define D DiGA
!define H HiMi_AuthZ
!define V Ver

title "Perform Pairing between DiGA and Device Data Recorder (detailed)"

actor V as "patient"

participant D order 1 [
	=DiGA
	----
	""Frontend | Backend""
]

participant H order 10 [
	=Device Data Recorder
	----
	""Frontend | Backend | AuthZ Server""
]

== 1. patient Initiates HiMi Pairing ==
ref over V, D : DiGA-specific login (out-of-scope)
V -> D: Initiate pairing with Device Data Recorder via DiGA frontend
activate V
activate D
D -> V: Present list of compatible Device Data Recorders via DiGA frontend
V -> D: Select Device Data Recorder via DiGA frontend
D -> V: Present list of compatible Personal Health Devices via DiGA frontend
V -> D: Select Personal Health Device via DiGA frontend
D -> V: Present required permissions via DiGA frontend
V -> D: Confirm permissions via DiGA frontend
||0||
deactivate V

== 2. Send Authorization Request to Device Data Recorder ==
D -> H: Retrieve Authorization Server Metadata Document
activate H
H -> D: Server Metadata Document
D -> D: Identify endpoints and scope (consent)
D -> D: Generate PKCE artifacts
D -> H: PAR with PKCE, tls_client_auth
D -> D: Authenticate HiMi (X.509 cert)
' The following checks are done against the registration data stored at Device Data Recorder during DiGA registration
H -> H: Authenticate DiGA (X.509 cert)
H -> H: Validate PAR (redirect_uri, scopes, ...)
H -> H: Store PAR and generate request_uri
H -> D: PAR response (request_uri, expires_in)
deactivate H

== 3. Authorization Confirmation by patient ==
D -> H: Authorization request for client_id, request_uri via frontend/user-agent redirect
activate H
H -> H: Validate authorization request and load PAR data
H -> V: Initiate login via system browser and possibly app link/deep link
activate V
ref over V, H : HiMi-specific login (out-of-scope)
H -> V: Present DiGA request with permissions via Device Data Recorder frontend
V -> H: Confirm permissions for DiGA via Device Data Recorder frontend
deactivate V
alt Pairing ID was previously generated and linked to user account
	H -> H: Locate pairing ID
else
	H -> H: Generate pairing ID and link to user account
end
H -> H: Generate consent for and with pairing ID and link to insured identity (HiMi)

== 4. Perform Authorization ==
H -> D: Authorization response with authz_code via frontend/user-agent redirect
D -> H: Token request with PKCE, tls_client_auth, and authz_code
D -> D: Authenticate HiMi (X.509 cert)
H -> H: Authenticate DiGA (X.509 cert)
H -> H: Validate PKCE and authz_code
H -> D: Token response (scope, pairing ID, access and refresh token with scope and pairing ID)

== 5. Complete Pairing ==
D -> D: Add DiGA prescription expiration date (patient) to consent
D -> D: Generate consent for pairing ID and link to patient's identity (DiGA)
D -> V: Confirm pairing via DiGA frontend
activate V
||0||
deactivate D
deactivate H
deactivate V

@enduml
