@startuml

!include fbeta-theme.puml
'!include gematik-theme.puml
hide footbox
!pragma teoz true

' ===== Aliases for participants =====
!define D DiGA
!define H AuthZ
!define V Ver

title "Pairing between DiGA and Device Data Recorder (detailed)"

actor V as "Patient"

participant D order 1 [
	=DiGA
	----
	""Frontend | Backend""
]

participant H order 10 [
	=Device Data Recorder
	----
	""Frontend | Backend | AuthZ Server""
]

== 1. Patient initiates Pairing with a Device Data Recorder ==
ref over V, D : DiGA-specific login (out-of-scope)
V -> D: Initiate pairing with Device Data Recorder via DiGA frontend
activate V
activate D
D -> V: Present list of compatible Device Data Recorders via DiGA frontend
V -> D: Select Device Data Recorder via DiGA frontend
D -> V: Present required permissions (based on Device Data Recorder scopes) via DiGA frontend
V -> D: Confirm permissions via DiGA frontend
||0||
deactivate V

== 2. Send Authorization Request to Device Data Recorder ==
D -> H: Retrieve Authorization Server Metadata Document
activate H
H -> D: Server Metadata Document
D -> D: Identify endpoints and scope (consent)
D -> D: Generate PKCE artifacts
D -> H: PAR with PKCE, client_id, tls_client_auth, scopes, redirect_uri
D -> D: Authenticate Device Data Recorder (FQDN, X.509 cert)
' The following checks are done against the registration data stored at Device Data Recorder during DiGA registration
H -> H: Authenticate DiGA (client_id, X.509 cert)
H -> H: Validate PAR (redirect_uri, scopes, ...)
H -> H: Store PAR and generate request_uri
H -> D: PAR response (request_uri, expires_in)
deactivate H

== 3. Authorization Confirmation by patient ==
D -> H: Authorization request via external user-agent redirect (client_id, request_uri)
activate H
H -> H: Validate authorization request and load PAR data
H -> V: Present login page in system browser
activate V
ref over V, H : Login specific to Device Data Recorder (out-of-scope)
H -> V: Present DiGA consent request with permissions in system browser
V -> H: Confirm permissions
deactivate V
alt Pairing ID was previously generated and linked to user account
	H -> H: Locate pairing ID
else
	H -> H: Generate pairing ID and link to user account
end
H -> H: Generate consent linked to the Pairing-ID and the patient identity

== 4. Perform Authorization ==
H -> D: Authorization response with authz_code via frontend/user-agent redirect
D -> H: Token request with PKCE, tls_client_auth, and authz_code
D -> D: Authenticate Device Data Recorder (FQDN, X.509 cert)
H -> H: Authenticate DiGA (client_id, X.509 cert)
H -> H: Validate PKCE and authz_code
H -> D: Token response (scope, pairing ID, access and refresh token with scope and pairing ID)

== 5. Complete Pairing ==
D -> D: Add DiGA prescription expiration date (patient) to consent
D -> D: Generate consent for pairing ID and link to patient's identity (DiGA)
D -> V: Confirm pairing via DiGA frontend
activate V
||0||
deactivate D
deactivate H
deactivate V

@enduml
