[IG]
#template = ./input/terminologit-template
#template = C:\Users\JieWu\Documents\nts\nts-git-dev-new\termgit-template-dev
template = ../fhir-ig-template
ig = fsh-generated/resources/ImplementationGuide-health-device-data-transfer.json